CREATE TABLE cms_foto_contest (
  contest_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  _parent_id INTEGER UNSIGNED NULL,
  caption_ru VARCHAR(255) NULL,
  caption_en VARCHAR(255) NULL,
  caption_ua VARCHAR(255) NULL,
  description_ru TEXT NULL,
  description_en TEXT NULL,
  description_ua TEXT NULL,
  full_description_ru MEDIUMTEXT NULL,
  full_description_en MEDIUMTEXT NULL,
  full_description_ua MEDIUMTEXT NULL,
  starts_from DATE NULL,
  ends_to DATE NULL,
  results_ru MEDIUMTEXT NULL,
  results_en MEDIUMTEXT NULL,
  results_ua MEDIUMTEXT NULL,
  expert_voting TINYINT UNSIGNED NULL,
  show_results_count INTEGER UNSIGNED NULL,
  contest_finished TINYINT UNSIGNED NULL,
  disable_voting TINYINT UNSIGNED NULL,
  active TINYINT UNSIGNED NOT NULL DEFAULT '0',
  _created_by INTEGER UNSIGNED NULL,
  _modified_by INTEGER UNSIGNED NULL,
  _lastmodified TIMESTAMP NOT NULL,
  total_voted INTEGER UNSIGNED NOT NULL DEFAULT '0',
  contest_logo VARCHAR(255) NULL,
  rotate_fotos TINYINT UNSIGNED NOT NULL DEFAULT '0',
  _priority INTEGER UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY(contest_id)
);

CREATE TABLE cms_foto (
  foto_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  contest_id INTEGER UNSIGNED NULL,
  caption_ru VARCHAR(255) NULL,
  caption_en VARCHAR(255) NULL,
  caption_ua VARCHAR(255) NULL,
  foto_file VARCHAR(255) NULL,
  foto_file_thumb VARCHAR(255) NULL,
  author_ru VARCHAR(255) NULL,
  author_en VARCHAR(255) NULL,
  author_ua VARCHAR(255) NULL,
  date_posted DATETIME NULL,
  description_ru TEXT NULL,
  description_ua TEXT NULL,
  description_en TEXT NULL,
  votes_count INTEGER UNSIGNED NOT NULL DEFAULT '0',
  active TINYINT UNSIGNED NOT NULL DEFAULT '0',
  _created_by INTEGER UNSIGNED NULL,
  _modified_by INTEGER UNSIGNED NULL,
  _lastmodified TIMESTAMP NOT NULL,
  shown TINYINT UNSIGNED NOT NULL DEFAULT '0',
  current_shown TINYINT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY(foto_id),
  INDEX cms_foto_FKIndex1(contest_id)
);