DROP TABLE url;
DROP TABLE urlinfo;
DROP TABLE dict;
DROP TABLE bdict;
# DROP TABLE bdict00;
# DROP TABLE bdictsw;
DROP TABLE crossdict;
DROP TABLE categories;
DROP TABLE qtrack;
DROP TABLE qinfo;
DROP TABLE server;
DROP TABLE srvinfo;
DROP TABLE links;
DROP TABLE wrdstat;
DROP TABLE fdicts;
DROP TABLE fdicti;
DROP TABLE fdictw;
